Protected the hookRemoveRunningTasks with concurrent conditions (v3)
bioinformatics-ua/dicoogle pull request #491
Opened 2021-08-10 19:24 UTC by bastiao

Protected the hookRemoveRunningTasks with concurrent conditions

2021-08-10 19:47 UTC, Enet4 requested changes

2021-08-10 19:47 UTC, Enet4 commented on dicoogle/src/main/java/pt/ua/dicoogle/taskManager/RunningIndexTasks.java
> +    private static boolean ENABLE_HOOK = Boolean.valueOf(System.getProperty("dicoole.tasks.removedCompleted", "true"));
You seem to have introduced a typo

2021-08-10 20:18 UTC, bastiao commented
To be honest, I'm thinking remove the insertion of this tasks, if they come from C-STORE SCP. 
It does not really add much information.

2021-08-11 10:46 UTC, Enet4 commented
This PR needs sync'ing with the changes proposed in #489.

> To be honest, I'm thinking remove the insertion of this tasks, if they come from C-STORE SCP.
> It does not really add much information.

We'd better discuss this further too.

2021-08-20 09:44 UTC, merged